# Generated by Django 6.0.3 on 2026-03-30 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerposition',
            name='ai_reasoning',
            field=models.TextField(blank=True, default='', help_text='LLM-generated explanation for why these parameter values were chosen.'),
        ),
        migrations.AddField(
            model_name='playerposition',
            name='ai_sources',
            field=models.TextField(blank=True, default='', help_text='Sources the LLM cited when determining these parameter values.'),
        ),
        migrations.AlterField(
            model_name='playerposition',
            name='flexibility',
            field=models.DecimalField(decimal_places=2, help_text='Willingness to compromise (0-100, higher = more flexible).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='scenarioissue',
            name='scale_max_label',
            field=models.CharField(help_text="Label for the 100 end of the scale (e.g. 'Complete embargo').", max_length=200),
        ),
        migrations.AlterField(
            model_name='scenarioissue',
            name='scale_min_label',
            field=models.CharField(help_text="Label for the 0 end of the scale (e.g. 'Full free trade').", max_length=200),
        ),
        migrations.AlterField(
            model_name='scenarioissue',
            name='status_quo_position',
            field=models.IntegerField(help_text='Current state on the scale. Anchors the model.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
